baseURL = 'https://www.inteliaedu.com/'
languageCode = 'en-us'
title = 'Intelia' 
themesDir = "themes"
theme = 'hugo-theme-stack'
[menu]
[[menu.social]]
  name = 'Youtube'
  url = 'https://www.youtube.com/channel/UCFi_GOHZiFGQHS6xbaGp_HQ'
  weight = 1
    [menu.social.params]
        icon = "brand-youtube"
        newTab = true
[[menu.social]]
  name = 'Linked In'
  url = 'https://www.linkedin.com/company/intelia-edu/'
  weight = 1
    [menu.social.params]
        icon = "brand-linkedin"
        newTab = true
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/inteliaedu/'
  weight = 1
    [menu.social.params]
        icon = "brand-github"
        newTab = true